name: personal_finance_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  flutter_local_notifications: ^19.1.0
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  intl: ^0.20.2
  fl_chart: ^0.71.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
